import { Channel, SettingsConfig, SubSnake, Stagebox } from '../types';

export interface HashableProjectData {
  inputs: Channel[];
  outputs: Channel[];
  settings: SettingsConfig;
  subSnakes: SubSnake[];
  stageboxes?: Stagebox[];
}

export async function calculateProjectHash(projectData: HashableProjectData): Promise<string> {
  // We stringify the subset of data that matters for content equality.
  // Using JSON.stringify directly relies on key order being consistent,
  // which is typically true for objects generated in the exact same flow,
  // but to be absolutely safe, we could deep-sort keys. For our purposes,
  // the data generated by usePatchState/export will have a consistent order.
  const payload = JSON.stringify({
    inputs: projectData.inputs,
    outputs: projectData.outputs,
    settings: projectData.settings,
    subSnakes: projectData.subSnakes,
    stageboxes: projectData.stageboxes,
  });
  
  try {
    const msgUint8 = new TextEncoder().encode(payload);
    const hashBuffer = await crypto.subtle.digest('SHA-256', msgUint8);
    const hashArray = Array.from(new Uint8Array(hashBuffer));
    return hashArray.map((b) => b.toString(16).padStart(2, '0')).join('');
  } catch (error) {
    console.error('SubtleCrypto is not available, falling back to simple hash', error);
    // Fallback simple string hash if subtle crypto is somehow not available
    let hash = 0;
    for (let i = 0; i < payload.length; i++) {
      const char = payload.charCodeAt(i);
      hash = ((hash << 5) - hash) + char;
      hash = hash & hash; // Convert to 32bit integer
    }
    return hash.toString(16);
  }
}
